title = "Test Guide"
author = "Johannes Biermann"
description = "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups."
hero_images = ["https://source.unsplash.com/1600x900/?nature,water", "https://source.unsplash.com/1600x900/?nature,water", "https://source.unsplash.com/1600x900/?nature,water"]
tags = ["museum", "test", "fruty"]